export { createWebGLRuntime } from "./lib/renderer/runtime";
export {
  defineWebGLEffect,
  defineWebGLSceneObjectEffect,
  createEffectDeclarations,
  type EffectDeclarationMap,
  type TypedEffectDeclaration,
  type WebGLEffectsDeclarationOf,
  type WebGLEffectBlendMode,
  type WebGLEffectCanvasDrawer,
  type WebGLEffectCanvasSurfaceHandle,
  type WebGLEffectContext,
  type WebGLEffectContentBoxShaderInput,
  type WebGLEffectDefinition,
  type WebGLEffectImageSequenceLayerHandle,
  type WebGLEffectMaterialLayerHandle,
  type WebGLEffectMaterialLayerHost,
  type WebGLEffectMaterialProgram,
  type WebGLEffectMediaShaderInputs,
  type WebGLEffectManagedObjectHandle,
  type WebGLEffectObjectFitShaderInput,
  type WebGLEffectPointLayerOptions,
  type WebGLEffectPostprocessHandle,
  type WebGLEffectPostprocessRequest,
  type WebGLEffectRenderableHandle,
  type WebGLEffectResourceScope,
  type WebGLEffectRuntimePostprocessFacade,
  type WebGLEffectRuntimeScope,
  type WebGLEffectSchedule,
  type WebGLEffectSceneScope,
  type WebGLSceneObjectEffectContext,
  type WebGLSceneObjectEffectDefinition,
  type WebGLSceneObjectEffectSourceKind,
  type WebGLSceneObjectPointerState,
  type WebGLEffectSetupContext,
  type WebGLEffectSourceTextureShaderInput,
  type WebGLEffectTimelineScope,
  type WebGLEffectSurfaceShaderInputs,
  type WebGLEffectTextLayerHandle,
  type WebGLEffectTextShaderInputs,
  type WebGLEffectTextureUniform,
  type WebGLEffectTextureLayerHandle,
  type WebGLEffectTextureTransform,
  type WebGLEffectUniformValue,
  type WebGLEffectUpdateContext,
  type WebGLEffectVideoLayerHandle,
  type WebGLRuntimePostprocessRequest,
  type WebGLModelEffectHandle,
  type WebGLModelMeshHandle,
  type WebGLTextGlyph,
  type WebGLTextGlyphRenderCommand,
  type WebGLTextLayerStyle,
} from "./lib/effects/effectAuthoring";
export type {
  WebGLEffectColorLike,
  WebGLEffectColorValue,
  WebGLEffectEmissiveLike,
} from "./lib/effects/effectColor";
export type {
  WebGLEffectAmbientLightRequest,
  WebGLEffectDirectionalLightRequest,
  WebGLEffectLightFollowMode,
  WebGLEffectLightsFacade,
  WebGLEffectPointLightRequest,
} from "./lib/effects/effectLights";
export type {
  WebGLEffectMaterialFacade,
  WebGLEffectMaterialLayerOptions,
} from "./lib/effects/effectMaterial";
export type {
  WebGLEffectAnimationBlendOptions,
  WebGLEffectAnimationCrossfadeOptions,
  WebGLEffectAnimationFacade,
  WebGLEffectAnimationPlayOptions,
  WebGLEffectAnimationScrubOptions,
  WebGLEffectModelFacade,
  WebGLEffectModelMeshesFacade,
  WebGLEffectModelMorphsFacade,
  WebGLEffectModelPointsFacade,
  WebGLEffectModelRigFacade,
  WebGLEffectModelSamplingFacade,
  WebGLEffectObjectHandle,
  WebGLEffectScaleLike,
  WebGLEffectTextFacade,
  WebGLEffectTextureFacade,
  WebGLEffectVector3Like,
  WebGLEffectVideoFacade,
} from "./lib/effects/effectObject";
export type {
  WebGLCameraDeclaration,
  WebGLCameraControllerDeclaration,
  WebGLCameraControllerEasing,
  WebGLCameraControllerFrameDeclaration,
  WebGLCameraControllerTimelineDeclaration,
  WebGLCameraFramingDeclaration,
  WebGLCameraGestureButton,
  WebGLCameraGestureDampingDeclaration,
  WebGLCameraGestureDragDeclaration,
  WebGLCameraGestureModifier,
  WebGLCameraGesturePointerControllerDeclaration,
  WebGLCameraGestureResetDeclaration,
  WebGLCameraMode,
  WebGLCameraDollyGestureDeclaration,
  WebGLCameraOrbitGestureDeclaration,
  WebGLCameraOrbitPointerControllerDeclaration,
  WebGLCameraPanGestureDeclaration,
  WebGLCameraPointerControllerDeclaration,
  WebGLCameraPointerParallaxDeclaration,
  WebGLCameraType,
  WebGLColorValue,
  WebGLDebugModelDiagnostic,
  WebGLDebugModelPrepareLoadState,
  WebGLDebugModelPrepareSummary,
  WebGLDebugModelSummary,
  WebGLDebugInteractionSummary,
  WebGLDebugSceneObjectInteractionSummary,
  WebGLDebugSceneObjectPointerSummary,
  WebGLDebugState,
  WebGLDeclaration,
  WebGLDOMAnchoredPlacementDeclaration,
  WebGLEffectsDeclaration,
  WebGLFrameInput,
  WebGLGateScrollBehavior,
  WebGLDOMSourceDeclaration,
  WebGLLifecycleDeclaration,
  WebGLLifecycleState,
  WebGLMediaImageSequenceSourceDeclaration,
  WebGLMediaImageSourceDeclaration,
  WebGLMediaSourceDeclaration,
  WebGLMediaVideoPlaybackDeclaration,
  WebGLMediaVideoSourceDeclaration,
  WebGLModelLoaderDeclaration,
  WebGLModelAnimationDeclaration,
  WebGLModelAnimationLoop,
  WebGLModelClipBlendDeclaration,
  WebGLModelClipPlaybackDeclaration,
  WebGLModelClipScrubDeclaration,
  WebGLModelDeclaration,
  WebGLModelMorphWeightDeclaration,
  WebGLModelPrepareDeclaration,
  WebGLModelSourceDeclaration,
  WebGLObjectPointerDeclaration,
  WebGLPickableDeclaration,
  WebGLPointerButton,
  WebGLPointerDeclaration,
  WebGLPointerModifiers,
  WebGLPointerState,
  WebGLTargetPointerState,
  WebGLPerformanceBudget,
  WebGLPerformanceWarning,
  WebGLProgressSignalSource,
  WebGLTimelineActiveRangeDeclaration,
  WebGLTimelineBindingDeclaration,
  WebGLRenderPassDeclaration,
  WebGLRenderRole,
  WebGLResourceStatus,
  WebGLRuntime,
  WebGLRuntimeOptions,
  WebGLScrollAdapter,
  WebGLScrollBehavior,
  WebGLScrollDeltaRouter,
  WebGLScrollGateState,
  WebGLScrollMetrics,
  WebGLOffscreenLifecycleDeclaration,
  WebGLOffscreenStrategy,
  WebGLImageSequenceFrame,
  WebGLLightDeclaration,
  WebGLLightKind,
  WebGLPlacementDeclaration,
  WebGLPlacementMode,
  WebGLPassViewportDeclaration,
  WebGLPostprocessDeclaration,
  WebGLPostprocessScopeDeclaration,
  WebGLSceneDeclaration,
  WebGLSceneProjection,
  WebGLScreenAnchor,
  WebGLScreenAnchoredPlacementDeclaration,
  WebGLScreenDepthPlacementDeclaration,
  WebGLScreenPlanePlacementDeclaration,
  WebGLSceneObjectInteractionDeclaration,
  WebGLSourceDeclaration,
  WebGLStageBoxDeclaration,
  WebGLStageMaterialDeclaration,
  WebGLStagePlaneDeclaration,
  WebGLStagePlaneRole,
  WebGLStagePrimitiveDeclaration,
  WebGLStagePrimitiveKind,
  WebGLStageLocalPlacementDeclaration,
  WebGLTransformScope,
  WebGLTuple2,
  WebGLTuple3,
} from "./lib/types";
